"""add_image_url_columns

Revision ID: 8b72c130fa6d
Revises: e6e6f1ab095c
Create Date: 2026-04-25 20:46:21.268705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b72c130fa6d'
down_revision: Union[str, None] = 'e6e6f1ab095c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('proof_photo_url', sa.String(length=500), nullable=True))
    op.add_column('operators', sa.Column('profile_picture_url', sa.String(length=500), nullable=True))
    op.add_column('riders', sa.Column('profile_picture_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('riders', 'profile_picture_url')
    op.drop_column('operators', 'profile_picture_url')
    op.drop_column('jobs', 'proof_photo_url')
    # ### end Alembic commands ###
