"""add_firebase_uid_to_operators

Revision ID: e6e6f1ab095c
Revises: 123263a3f5ee
Create Date: 2026-04-25 20:35:59.269478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6e6f1ab095c'
down_revision: Union[str, None] = '123263a3f5ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('operators', sa.Column('firebase_uid', sa.String(length=128), nullable=True))
    op.alter_column('operators', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.create_index(op.f('ix_operators_firebase_uid'), 'operators', ['firebase_uid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_operators_firebase_uid'), table_name='operators')
    op.alter_column('operators', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('operators', 'firebase_uid')
    # ### end Alembic commands ###
