/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'primary': '#000000',
        'on-primary': '#ffffff',
        'primary-container': '#1c1b1d',
        'on-primary-container': '#858386',
        'secondary': '#5f5e61',
        'on-secondary': '#ffffff',
        'secondary-container': '#e4e1e5',
        'on-secondary-container': '#656467',
        'surface': '#fdf8f8',
        'surface-bright': '#fdf8f8',
        'surface-dim': '#ddd9d9',
        'surface-variant': '#e5e2e1',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f7f3f2',
        'surface-container': '#f1edec',
        'surface-container-high': '#ebe7e7',
        'surface-container-highest': '#e5e2e1',
        'on-surface': '#1c1b1b',
        'on-surface-variant': '#47464a',
        'outline': '#78767b',
        'outline-variant': '#c8c5ca',
        'error': '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'background': '#fdf8f8',
        'on-background': '#1c1b1b',
        'secondary-fixed-dim': '#c8c6c9',
        'tertiary': '#000000',
        'on-tertiary': '#ffffff',
      },
      spacing: {
        'xs': '4px',
        'sm': '8px',
        'md': '16px',
        'lg': '24px',
        'xl': '32px',
        'xxl': '64px',
        'gutter': '24px',
        'margin': '32px',
      },
      fontFamily: {
        'sans': ['Inter', 'sans-serif'],
        'mono': ['ui-monospace', 'SFMono-Regular', 'Menlo', 'Monaco', 'Consolas', 'monospace'],
      },
      fontSize: {
        'h1': ['40px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
        'h2': ['30px', { lineHeight: '1.3', letterSpacing: '-0.01em', fontWeight: '600' }],
        'h3': ['24px', { lineHeight: '1.4', letterSpacing: '0', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.6', letterSpacing: '0', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.5', letterSpacing: '0', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '1.5', letterSpacing: '0', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '1', letterSpacing: '0.05em', fontWeight: '600' }],
        'mono-label': ['13px', { lineHeight: '1', letterSpacing: '0', fontWeight: '500' }],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        'full': '9999px',
      },
      boxShadow: {
        'card': '0px 4px 12px rgba(0,0,0,0.05)',
        'elevated': '0px 12px 32px rgba(0,0,0,0.1)',
        'sheet': '0px -12px 32px rgba(0,0,0,0.08)',
      },
    },
  },
  plugins: [],
}
